//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_WorkFlow.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUserData
    {
        public long C_idx { get; set; }
        public long C_IdData { get; set; }
        public string C_emailData { get; set; }
        public string C_nickNameData { get; set; }
        public string C_profileData { get; set; }
        public string C_snsNameData { get; set; }
    }
}
