//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_WorkFlow.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WORKFLOWDB : DbContext
    {
        public WORKFLOWDB()
            : base("name=WORKFLOWDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblUserData> TblUserData { get; set; }
    
        public virtual ObjectResult<uspGetUserData_Result> uspGetUserData(Nullable<long> p_idx, Nullable<long> p_IdData, string p_nickNameData, string p_snsNameData)
        {
            var p_idxParameter = p_idx.HasValue ?
                new ObjectParameter("p_idx", p_idx) :
                new ObjectParameter("p_idx", typeof(long));
    
            var p_IdDataParameter = p_IdData.HasValue ?
                new ObjectParameter("p_IdData", p_IdData) :
                new ObjectParameter("p_IdData", typeof(long));
    
            var p_nickNameDataParameter = p_nickNameData != null ?
                new ObjectParameter("p_nickNameData", p_nickNameData) :
                new ObjectParameter("p_nickNameData", typeof(string));
    
            var p_snsNameDataParameter = p_snsNameData != null ?
                new ObjectParameter("p_snsNameData", p_snsNameData) :
                new ObjectParameter("p_snsNameData", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetUserData_Result>("uspGetUserData", p_idxParameter, p_IdDataParameter, p_nickNameDataParameter, p_snsNameDataParameter);
        }
    
        public virtual ObjectResult<uspInsertUserData_Result> uspInsertUserData(Nullable<long> p_IdData, string p_nickNameData, string p_snsNameData, ObjectParameter resultCode)
        {
            var p_IdDataParameter = p_IdData.HasValue ?
                new ObjectParameter("p_IdData", p_IdData) :
                new ObjectParameter("p_IdData", typeof(long));
    
            var p_nickNameDataParameter = p_nickNameData != null ?
                new ObjectParameter("p_nickNameData", p_nickNameData) :
                new ObjectParameter("p_nickNameData", typeof(string));
    
            var p_snsNameDataParameter = p_snsNameData != null ?
                new ObjectParameter("p_snsNameData", p_snsNameData) :
                new ObjectParameter("p_snsNameData", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspInsertUserData_Result>("uspInsertUserData", p_IdDataParameter, p_nickNameDataParameter, p_snsNameDataParameter, resultCode);
        }
    }
}
